name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Build
      run: go build -v ./...

  tests:
    # Задание "tests" зависит от задания "build" и будет выполнено после него
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4

    - name: Start App for tests
      run: go run main.go & for attempt in {1..20}; do sleep 3;

    - name: Test
      run: go test -v ./...