name: golang-pipeline
on:
  push:
    branches: ["main"]
    tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
      - uses: JarvusInnovations/background-action@v1
        name: Bootstrap System Under Test (SUT)
        with:
            run: |
                go run main.go
            wait-on: |
                http://localhost:7540
            tail: true # true = stderr,stdout
            log-output-resume: stderr
            wait-for: 5m
            log-output: stderr,stdout # same as true
        
      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test ./tests

      - name: Vet
        run: |
          go vet ./...

  push-docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: gt814/final-github-workflow

      - name: Build and push Docker Inage
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}